# Generated by Django 5.2.2 on 2025-06-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата оплаты')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус заказа')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код статуса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный статус')),
            ],
            options={
                'verbose_name': 'статус заказа',
                'verbose_name_plural': 'статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Способ оплаты')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код способа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
            options={
                'verbose_name': 'способ оплаты',
                'verbose_name_plural': 'способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес (г)')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='Время приготовления (мин)')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Острое')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Вегетарианское')),
                ('photo', models.ImageField(upload_to='menu_items/', verbose_name='Фото')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop2.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'позиция меню',
                'verbose_name_plural': 'позиции меню',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop2.cart', verbose_name='Корзина')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop2.menuitem', verbose_name='Позиция меню')),
            ],
            options={
                'verbose_name': 'элемент корзины',
                'verbose_name_plural': 'элементы корзины',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за единицу')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop2.menuitem', verbose_name='Позиция меню')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop2.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'элемент заказа',
                'verbose_name_plural': 'элементы заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop2.orderstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop2.paymentmethod', verbose_name='Способ оплаты'),
        ),
    ]
