# Generated by Django 5.2.2 on 2025-06-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0002_remove_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ManyToManyField(through='shop2.OrderItem', to='shop2.menuitem', verbose_name='Позиция меню'),
        ),
    ]
